package protoClass;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor.proto

public final class SensorOuterClass {
  private SensorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sensor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Sensor.SensorType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .Sensor.SensorType type = 1;</code>
     */
    SensorOuterClass.Sensor.SensorType getType();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>required float state = 3;</code>
     */
    boolean hasState();
    /**
     * <code>required float state = 3;</code>
     */
    float getState();

    /**
     * <code>required .time data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>required .time data = 4;</code>
     */
    SensorOuterClass.time getData();
    /**
     * <code>required .time data = 4;</code>
     */
    SensorOuterClass.timeOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code Sensor}
   */
  public  static final class Sensor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Sensor)
      SensorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sensor.newBuilder() to construct.
    private Sensor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sensor() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Sensor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sensor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              SensorOuterClass.Sensor.SensorType value = SensorOuterClass.Sensor.SensorType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              state_ = input.readFloat();
              break;
            }
            case 34: {
              SensorOuterClass.time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(SensorOuterClass.time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SensorOuterClass.internal_static_Sensor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SensorOuterClass.internal_static_Sensor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SensorOuterClass.Sensor.class, SensorOuterClass.Sensor.Builder.class);
    }

    /**
     * Protobuf enum {@code Sensor.SensorType}
     */
    public enum SensorType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEMPERATURE = 0;</code>
       */
      TEMPERATURE(0),
      /**
       * <code>LIGHT = 1;</code>
       */
      LIGHT(1),
      /**
       * <code>LUMINOSITY = 2;</code>
       */
      LUMINOSITY(2),
      ;

      /**
       * <code>TEMPERATURE = 0;</code>
       */
      public static final int TEMPERATURE_VALUE = 0;
      /**
       * <code>LIGHT = 1;</code>
       */
      public static final int LIGHT_VALUE = 1;
      /**
       * <code>LUMINOSITY = 2;</code>
       */
      public static final int LUMINOSITY_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SensorType valueOf(int value) {
        return forNumber(value);
      }

      public static SensorType forNumber(int value) {
        switch (value) {
          case 0: return TEMPERATURE;
          case 1: return LIGHT;
          case 2: return LUMINOSITY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SensorType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SensorType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SensorType>() {
              public SensorType findValueByNumber(int number) {
                return SensorType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SensorOuterClass.Sensor.getDescriptor().getEnumTypes().get(0);
      }

      private static final SensorType[] VALUES = values();

      public static SensorType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SensorType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Sensor.SensorType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .Sensor.SensorType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .Sensor.SensorType type = 1;</code>
     */
    public SensorOuterClass.Sensor.SensorType getType() {
      @SuppressWarnings("deprecation")
      SensorOuterClass.Sensor.SensorType result = SensorOuterClass.Sensor.SensorType.valueOf(type_);
      return result == null ? SensorOuterClass.Sensor.SensorType.TEMPERATURE : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private float state_;
    /**
     * <code>required float state = 3;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float state = 3;</code>
     */
    public float getState() {
      return state_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private SensorOuterClass.time data_;
    /**
     * <code>required .time data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .time data = 4;</code>
     */
    public SensorOuterClass.time getData() {
      return data_ == null ? SensorOuterClass.time.getDefaultInstance() : data_;
    }
    /**
     * <code>required .time data = 4;</code>
     */
    public SensorOuterClass.timeOrBuilder getDataOrBuilder() {
      return data_ == null ? SensorOuterClass.time.getDefaultInstance() : data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, state_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, state_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SensorOuterClass.Sensor)) {
        return super.equals(obj);
      }
      SensorOuterClass.Sensor other = (SensorOuterClass.Sensor) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (java.lang.Float.floatToIntBits(getState())
            != java.lang.Float.floatToIntBits(
                other.getState())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getState());
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SensorOuterClass.Sensor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.Sensor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.Sensor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.Sensor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.Sensor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.Sensor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.Sensor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorOuterClass.Sensor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorOuterClass.Sensor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SensorOuterClass.Sensor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorOuterClass.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorOuterClass.Sensor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SensorOuterClass.Sensor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sensor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sensor)
        SensorOuterClass.SensorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SensorOuterClass.internal_static_Sensor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SensorOuterClass.internal_static_Sensor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SensorOuterClass.Sensor.class, SensorOuterClass.Sensor.Builder.class);
      }

      // Construct using SensorOuterClass.Sensor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SensorOuterClass.internal_static_Sensor_descriptor;
      }

      @java.lang.Override
      public SensorOuterClass.Sensor getDefaultInstanceForType() {
        return SensorOuterClass.Sensor.getDefaultInstance();
      }

      @java.lang.Override
      public SensorOuterClass.Sensor build() {
        SensorOuterClass.Sensor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SensorOuterClass.Sensor buildPartial() {
        SensorOuterClass.Sensor result = new SensorOuterClass.Sensor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.state_ = state_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (dataBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = dataBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SensorOuterClass.Sensor) {
          return mergeFrom((SensorOuterClass.Sensor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SensorOuterClass.Sensor other) {
        if (other == SensorOuterClass.Sensor.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasState()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        if (!getData().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SensorOuterClass.Sensor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SensorOuterClass.Sensor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .Sensor.SensorType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .Sensor.SensorType type = 1;</code>
       */
      public SensorOuterClass.Sensor.SensorType getType() {
        @SuppressWarnings("deprecation")
        SensorOuterClass.Sensor.SensorType result = SensorOuterClass.Sensor.SensorType.valueOf(type_);
        return result == null ? SensorOuterClass.Sensor.SensorType.TEMPERATURE : result;
      }
      /**
       * <code>required .Sensor.SensorType type = 1;</code>
       */
      public Builder setType(SensorOuterClass.Sensor.SensorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Sensor.SensorType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private float state_ ;
      /**
       * <code>required float state = 3;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float state = 3;</code>
       */
      public float getState() {
        return state_;
      }
      /**
       * <code>required float state = 3;</code>
       */
      public Builder setState(float value) {
        bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float state = 3;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0F;
        onChanged();
        return this;
      }

      private SensorOuterClass.time data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          SensorOuterClass.time, SensorOuterClass.time.Builder, SensorOuterClass.timeOrBuilder> dataBuilder_;
      /**
       * <code>required .time data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required .time data = 4;</code>
       */
      public SensorOuterClass.time getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? SensorOuterClass.time.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>required .time data = 4;</code>
       */
      public Builder setData(SensorOuterClass.time value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .time data = 4;</code>
       */
      public Builder setData(
          SensorOuterClass.time.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .time data = 4;</code>
       */
      public Builder mergeData(SensorOuterClass.time value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              data_ != null &&
              data_ != SensorOuterClass.time.getDefaultInstance()) {
            data_ =
              SensorOuterClass.time.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .time data = 4;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .time data = 4;</code>
       */
      public SensorOuterClass.time.Builder getDataBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>required .time data = 4;</code>
       */
      public SensorOuterClass.timeOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              SensorOuterClass.time.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>required .time data = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SensorOuterClass.time, SensorOuterClass.time.Builder, SensorOuterClass.timeOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SensorOuterClass.time, SensorOuterClass.time.Builder, SensorOuterClass.timeOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Sensor)
    }

    // @@protoc_insertion_point(class_scope:Sensor)
    private static final SensorOuterClass.Sensor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SensorOuterClass.Sensor();
    }

    public static SensorOuterClass.Sensor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Sensor>
        PARSER = new com.google.protobuf.AbstractParser<Sensor>() {
      @java.lang.Override
      public Sensor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sensor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sensor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sensor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SensorOuterClass.Sensor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface timeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:time)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 seconds = 1;</code>
     */
    boolean hasSeconds();
    /**
     * <code>required int32 seconds = 1;</code>
     */
    int getSeconds();

    /**
     * <code>required int32 minutes = 2;</code>
     */
    boolean hasMinutes();
    /**
     * <code>required int32 minutes = 2;</code>
     */
    int getMinutes();

    /**
     * <code>required int32 hours = 3;</code>
     */
    boolean hasHours();
    /**
     * <code>required int32 hours = 3;</code>
     */
    int getHours();

    /**
     * <code>required int32 day = 4;</code>
     */
    boolean hasDay();
    /**
     * <code>required int32 day = 4;</code>
     */
    int getDay();

    /**
     * <code>required int32 month = 5;</code>
     */
    boolean hasMonth();
    /**
     * <code>required int32 month = 5;</code>
     */
    int getMonth();

    /**
     * <code>required int32 year = 6;</code>
     */
    boolean hasYear();
    /**
     * <code>required int32 year = 6;</code>
     */
    int getYear();
  }
  /**
   * Protobuf type {@code time}
   */
  public  static final class time extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:time)
      timeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use time.newBuilder() to construct.
    private time(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private time() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new time();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private time(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              seconds_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              minutes_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              hours_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              day_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              month_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              year_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SensorOuterClass.internal_static_time_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SensorOuterClass.internal_static_time_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SensorOuterClass.time.class, SensorOuterClass.time.Builder.class);
    }

    private int bitField0_;
    public static final int SECONDS_FIELD_NUMBER = 1;
    private int seconds_;
    /**
     * <code>required int32 seconds = 1;</code>
     */
    public boolean hasSeconds() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 seconds = 1;</code>
     */
    public int getSeconds() {
      return seconds_;
    }

    public static final int MINUTES_FIELD_NUMBER = 2;
    private int minutes_;
    /**
     * <code>required int32 minutes = 2;</code>
     */
    public boolean hasMinutes() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 minutes = 2;</code>
     */
    public int getMinutes() {
      return minutes_;
    }

    public static final int HOURS_FIELD_NUMBER = 3;
    private int hours_;
    /**
     * <code>required int32 hours = 3;</code>
     */
    public boolean hasHours() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 hours = 3;</code>
     */
    public int getHours() {
      return hours_;
    }

    public static final int DAY_FIELD_NUMBER = 4;
    private int day_;
    /**
     * <code>required int32 day = 4;</code>
     */
    public boolean hasDay() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 day = 4;</code>
     */
    public int getDay() {
      return day_;
    }

    public static final int MONTH_FIELD_NUMBER = 5;
    private int month_;
    /**
     * <code>required int32 month = 5;</code>
     */
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 month = 5;</code>
     */
    public int getMonth() {
      return month_;
    }

    public static final int YEAR_FIELD_NUMBER = 6;
    private int year_;
    /**
     * <code>required int32 year = 6;</code>
     */
    public boolean hasYear() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 year = 6;</code>
     */
    public int getYear() {
      return year_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSeconds()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinutes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHours()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMonth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYear()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, seconds_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, minutes_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, hours_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, day_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, month_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, year_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seconds_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minutes_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hours_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, day_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, month_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, year_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SensorOuterClass.time)) {
        return super.equals(obj);
      }
      SensorOuterClass.time other = (SensorOuterClass.time) obj;

      if (hasSeconds() != other.hasSeconds()) return false;
      if (hasSeconds()) {
        if (getSeconds()
            != other.getSeconds()) return false;
      }
      if (hasMinutes() != other.hasMinutes()) return false;
      if (hasMinutes()) {
        if (getMinutes()
            != other.getMinutes()) return false;
      }
      if (hasHours() != other.hasHours()) return false;
      if (hasHours()) {
        if (getHours()
            != other.getHours()) return false;
      }
      if (hasDay() != other.hasDay()) return false;
      if (hasDay()) {
        if (getDay()
            != other.getDay()) return false;
      }
      if (hasMonth() != other.hasMonth()) return false;
      if (hasMonth()) {
        if (getMonth()
            != other.getMonth()) return false;
      }
      if (hasYear() != other.hasYear()) return false;
      if (hasYear()) {
        if (getYear()
            != other.getYear()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSeconds()) {
        hash = (37 * hash) + SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + getSeconds();
      }
      if (hasMinutes()) {
        hash = (37 * hash) + MINUTES_FIELD_NUMBER;
        hash = (53 * hash) + getMinutes();
      }
      if (hasHours()) {
        hash = (37 * hash) + HOURS_FIELD_NUMBER;
        hash = (53 * hash) + getHours();
      }
      if (hasDay()) {
        hash = (37 * hash) + DAY_FIELD_NUMBER;
        hash = (53 * hash) + getDay();
      }
      if (hasMonth()) {
        hash = (37 * hash) + MONTH_FIELD_NUMBER;
        hash = (53 * hash) + getMonth();
      }
      if (hasYear()) {
        hash = (37 * hash) + YEAR_FIELD_NUMBER;
        hash = (53 * hash) + getYear();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SensorOuterClass.time parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.time parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.time parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.time parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.time parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.time parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.time parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorOuterClass.time parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorOuterClass.time parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SensorOuterClass.time parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorOuterClass.time parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorOuterClass.time parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SensorOuterClass.time prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code time}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:time)
        SensorOuterClass.timeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SensorOuterClass.internal_static_time_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SensorOuterClass.internal_static_time_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SensorOuterClass.time.class, SensorOuterClass.time.Builder.class);
      }

      // Construct using SensorOuterClass.time.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seconds_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        minutes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hours_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        day_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        month_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        year_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SensorOuterClass.internal_static_time_descriptor;
      }

      @java.lang.Override
      public SensorOuterClass.time getDefaultInstanceForType() {
        return SensorOuterClass.time.getDefaultInstance();
      }

      @java.lang.Override
      public SensorOuterClass.time build() {
        SensorOuterClass.time result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SensorOuterClass.time buildPartial() {
        SensorOuterClass.time result = new SensorOuterClass.time(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.seconds_ = seconds_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.minutes_ = minutes_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hours_ = hours_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.day_ = day_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.month_ = month_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.year_ = year_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SensorOuterClass.time) {
          return mergeFrom((SensorOuterClass.time)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SensorOuterClass.time other) {
        if (other == SensorOuterClass.time.getDefaultInstance()) return this;
        if (other.hasSeconds()) {
          setSeconds(other.getSeconds());
        }
        if (other.hasMinutes()) {
          setMinutes(other.getMinutes());
        }
        if (other.hasHours()) {
          setHours(other.getHours());
        }
        if (other.hasDay()) {
          setDay(other.getDay());
        }
        if (other.hasMonth()) {
          setMonth(other.getMonth());
        }
        if (other.hasYear()) {
          setYear(other.getYear());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSeconds()) {
          return false;
        }
        if (!hasMinutes()) {
          return false;
        }
        if (!hasHours()) {
          return false;
        }
        if (!hasDay()) {
          return false;
        }
        if (!hasMonth()) {
          return false;
        }
        if (!hasYear()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SensorOuterClass.time parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SensorOuterClass.time) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int seconds_ ;
      /**
       * <code>required int32 seconds = 1;</code>
       */
      public boolean hasSeconds() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 seconds = 1;</code>
       */
      public int getSeconds() {
        return seconds_;
      }
      /**
       * <code>required int32 seconds = 1;</code>
       */
      public Builder setSeconds(int value) {
        bitField0_ |= 0x00000001;
        seconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seconds = 1;</code>
       */
      public Builder clearSeconds() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seconds_ = 0;
        onChanged();
        return this;
      }

      private int minutes_ ;
      /**
       * <code>required int32 minutes = 2;</code>
       */
      public boolean hasMinutes() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 minutes = 2;</code>
       */
      public int getMinutes() {
        return minutes_;
      }
      /**
       * <code>required int32 minutes = 2;</code>
       */
      public Builder setMinutes(int value) {
        bitField0_ |= 0x00000002;
        minutes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 minutes = 2;</code>
       */
      public Builder clearMinutes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minutes_ = 0;
        onChanged();
        return this;
      }

      private int hours_ ;
      /**
       * <code>required int32 hours = 3;</code>
       */
      public boolean hasHours() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 hours = 3;</code>
       */
      public int getHours() {
        return hours_;
      }
      /**
       * <code>required int32 hours = 3;</code>
       */
      public Builder setHours(int value) {
        bitField0_ |= 0x00000004;
        hours_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 hours = 3;</code>
       */
      public Builder clearHours() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hours_ = 0;
        onChanged();
        return this;
      }

      private int day_ ;
      /**
       * <code>required int32 day = 4;</code>
       */
      public boolean hasDay() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 day = 4;</code>
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>required int32 day = 4;</code>
       */
      public Builder setDay(int value) {
        bitField0_ |= 0x00000008;
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 day = 4;</code>
       */
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000008);
        day_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <code>required int32 month = 5;</code>
       */
      public boolean hasMonth() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 month = 5;</code>
       */
      public int getMonth() {
        return month_;
      }
      /**
       * <code>required int32 month = 5;</code>
       */
      public Builder setMonth(int value) {
        bitField0_ |= 0x00000010;
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 month = 5;</code>
       */
      public Builder clearMonth() {
        bitField0_ = (bitField0_ & ~0x00000010);
        month_ = 0;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>required int32 year = 6;</code>
       */
      public boolean hasYear() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int32 year = 6;</code>
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>required int32 year = 6;</code>
       */
      public Builder setYear(int value) {
        bitField0_ |= 0x00000020;
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 year = 6;</code>
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000020);
        year_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:time)
    }

    // @@protoc_insertion_point(class_scope:time)
    private static final SensorOuterClass.time DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SensorOuterClass.time();
    }

    public static SensorOuterClass.time getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<time>
        PARSER = new com.google.protobuf.AbstractParser<time>() {
      @java.lang.Override
      public time parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new time(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<time> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<time> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SensorOuterClass.time getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommandMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommandMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .CommandMessage.CommandType command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>required .CommandMessage.CommandType command = 1;</code>
     */
    SensorOuterClass.CommandMessage.CommandType getCommand();

    /**
     * <code>optional .Sensor parameter = 2;</code>
     */
    boolean hasParameter();
    /**
     * <code>optional .Sensor parameter = 2;</code>
     */
    SensorOuterClass.Sensor getParameter();
    /**
     * <code>optional .Sensor parameter = 2;</code>
     */
    SensorOuterClass.SensorOrBuilder getParameterOrBuilder();
  }
  /**
   * Protobuf type {@code CommandMessage}
   */
  public  static final class CommandMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommandMessage)
      CommandMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandMessage.newBuilder() to construct.
    private CommandMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandMessage() {
      command_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommandMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              SensorOuterClass.CommandMessage.CommandType value = SensorOuterClass.CommandMessage.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                command_ = rawValue;
              }
              break;
            }
            case 18: {
              SensorOuterClass.Sensor.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = parameter_.toBuilder();
              }
              parameter_ = input.readMessage(SensorOuterClass.Sensor.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(parameter_);
                parameter_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SensorOuterClass.internal_static_CommandMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SensorOuterClass.internal_static_CommandMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SensorOuterClass.CommandMessage.class, SensorOuterClass.CommandMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code CommandMessage.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GET_STATE = 0;</code>
       */
      GET_STATE(0),
      /**
       * <code>SET_STATE = 1;</code>
       */
      SET_STATE(1),
      /**
       * <code>SENSOR_STATE = 2;</code>
       */
      SENSOR_STATE(2),
      ;

      /**
       * <code>GET_STATE = 0;</code>
       */
      public static final int GET_STATE_VALUE = 0;
      /**
       * <code>SET_STATE = 1;</code>
       */
      public static final int SET_STATE_VALUE = 1;
      /**
       * <code>SENSOR_STATE = 2;</code>
       */
      public static final int SENSOR_STATE_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CommandType valueOf(int value) {
        return forNumber(value);
      }

      public static CommandType forNumber(int value) {
        switch (value) {
          case 0: return GET_STATE;
          case 1: return SET_STATE;
          case 2: return SENSOR_STATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CommandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SensorOuterClass.CommandMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CommandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CommandMessage.CommandType)
    }

    private int bitField0_;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>required .CommandMessage.CommandType command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .CommandMessage.CommandType command = 1;</code>
     */
    public SensorOuterClass.CommandMessage.CommandType getCommand() {
      @SuppressWarnings("deprecation")
      SensorOuterClass.CommandMessage.CommandType result = SensorOuterClass.CommandMessage.CommandType.valueOf(command_);
      return result == null ? SensorOuterClass.CommandMessage.CommandType.GET_STATE : result;
    }

    public static final int PARAMETER_FIELD_NUMBER = 2;
    private SensorOuterClass.Sensor parameter_;
    /**
     * <code>optional .Sensor parameter = 2;</code>
     */
    public boolean hasParameter() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .Sensor parameter = 2;</code>
     */
    public SensorOuterClass.Sensor getParameter() {
      return parameter_ == null ? SensorOuterClass.Sensor.getDefaultInstance() : parameter_;
    }
    /**
     * <code>optional .Sensor parameter = 2;</code>
     */
    public SensorOuterClass.SensorOrBuilder getParameterOrBuilder() {
      return parameter_ == null ? SensorOuterClass.Sensor.getDefaultInstance() : parameter_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasParameter()) {
        if (!getParameter().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, command_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getParameter());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getParameter());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SensorOuterClass.CommandMessage)) {
        return super.equals(obj);
      }
      SensorOuterClass.CommandMessage other = (SensorOuterClass.CommandMessage) obj;

      if (hasCommand() != other.hasCommand()) return false;
      if (hasCommand()) {
        if (command_ != other.command_) return false;
      }
      if (hasParameter() != other.hasParameter()) return false;
      if (hasParameter()) {
        if (!getParameter()
            .equals(other.getParameter())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCommand()) {
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + command_;
      }
      if (hasParameter()) {
        hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + getParameter().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SensorOuterClass.CommandMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.CommandMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.CommandMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.CommandMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.CommandMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SensorOuterClass.CommandMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SensorOuterClass.CommandMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorOuterClass.CommandMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorOuterClass.CommandMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SensorOuterClass.CommandMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SensorOuterClass.CommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SensorOuterClass.CommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SensorOuterClass.CommandMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommandMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommandMessage)
        SensorOuterClass.CommandMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SensorOuterClass.internal_static_CommandMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SensorOuterClass.internal_static_CommandMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SensorOuterClass.CommandMessage.class, SensorOuterClass.CommandMessage.Builder.class);
      }

      // Construct using SensorOuterClass.CommandMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParameterFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        command_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (parameterBuilder_ == null) {
          parameter_ = null;
        } else {
          parameterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SensorOuterClass.internal_static_CommandMessage_descriptor;
      }

      @java.lang.Override
      public SensorOuterClass.CommandMessage getDefaultInstanceForType() {
        return SensorOuterClass.CommandMessage.getDefaultInstance();
      }

      @java.lang.Override
      public SensorOuterClass.CommandMessage build() {
        SensorOuterClass.CommandMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SensorOuterClass.CommandMessage buildPartial() {
        SensorOuterClass.CommandMessage result = new SensorOuterClass.CommandMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (parameterBuilder_ == null) {
            result.parameter_ = parameter_;
          } else {
            result.parameter_ = parameterBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SensorOuterClass.CommandMessage) {
          return mergeFrom((SensorOuterClass.CommandMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SensorOuterClass.CommandMessage other) {
        if (other == SensorOuterClass.CommandMessage.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasParameter()) {
          mergeParameter(other.getParameter());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCommand()) {
          return false;
        }
        if (hasParameter()) {
          if (!getParameter().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SensorOuterClass.CommandMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SensorOuterClass.CommandMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int command_ = 0;
      /**
       * <code>required .CommandMessage.CommandType command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .CommandMessage.CommandType command = 1;</code>
       */
      public SensorOuterClass.CommandMessage.CommandType getCommand() {
        @SuppressWarnings("deprecation")
        SensorOuterClass.CommandMessage.CommandType result = SensorOuterClass.CommandMessage.CommandType.valueOf(command_);
        return result == null ? SensorOuterClass.CommandMessage.CommandType.GET_STATE : result;
      }
      /**
       * <code>required .CommandMessage.CommandType command = 1;</code>
       */
      public Builder setCommand(SensorOuterClass.CommandMessage.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .CommandMessage.CommandType command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = 0;
        onChanged();
        return this;
      }

      private SensorOuterClass.Sensor parameter_;
      private com.google.protobuf.SingleFieldBuilderV3<
          SensorOuterClass.Sensor, SensorOuterClass.Sensor.Builder, SensorOuterClass.SensorOrBuilder> parameterBuilder_;
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public boolean hasParameter() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public SensorOuterClass.Sensor getParameter() {
        if (parameterBuilder_ == null) {
          return parameter_ == null ? SensorOuterClass.Sensor.getDefaultInstance() : parameter_;
        } else {
          return parameterBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public Builder setParameter(SensorOuterClass.Sensor value) {
        if (parameterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          parameter_ = value;
          onChanged();
        } else {
          parameterBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public Builder setParameter(
          SensorOuterClass.Sensor.Builder builderForValue) {
        if (parameterBuilder_ == null) {
          parameter_ = builderForValue.build();
          onChanged();
        } else {
          parameterBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public Builder mergeParameter(SensorOuterClass.Sensor value) {
        if (parameterBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              parameter_ != null &&
              parameter_ != SensorOuterClass.Sensor.getDefaultInstance()) {
            parameter_ =
              SensorOuterClass.Sensor.newBuilder(parameter_).mergeFrom(value).buildPartial();
          } else {
            parameter_ = value;
          }
          onChanged();
        } else {
          parameterBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public Builder clearParameter() {
        if (parameterBuilder_ == null) {
          parameter_ = null;
          onChanged();
        } else {
          parameterBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public SensorOuterClass.Sensor.Builder getParameterBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getParameterFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      public SensorOuterClass.SensorOrBuilder getParameterOrBuilder() {
        if (parameterBuilder_ != null) {
          return parameterBuilder_.getMessageOrBuilder();
        } else {
          return parameter_ == null ?
              SensorOuterClass.Sensor.getDefaultInstance() : parameter_;
        }
      }
      /**
       * <code>optional .Sensor parameter = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SensorOuterClass.Sensor, SensorOuterClass.Sensor.Builder, SensorOuterClass.SensorOrBuilder> 
          getParameterFieldBuilder() {
        if (parameterBuilder_ == null) {
          parameterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SensorOuterClass.Sensor, SensorOuterClass.Sensor.Builder, SensorOuterClass.SensorOrBuilder>(
                  getParameter(),
                  getParentForChildren(),
                  isClean());
          parameter_ = null;
        }
        return parameterBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommandMessage)
    }

    // @@protoc_insertion_point(class_scope:CommandMessage)
    private static final SensorOuterClass.CommandMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SensorOuterClass.CommandMessage();
    }

    public static SensorOuterClass.CommandMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CommandMessage>
        PARSER = new com.google.protobuf.AbstractParser<CommandMessage>() {
      @java.lang.Override
      public CommandMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SensorOuterClass.CommandMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sensor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sensor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_time_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_time_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sensor.proto\"\224\001\n\006Sensor\022 \n\004type\030\001 \002(\0162" +
      "\022.Sensor.SensorType\022\n\n\002id\030\002 \002(\005\022\r\n\005state" +
      "\030\003 \002(\002\022\023\n\004data\030\004 \002(\0132\005.time\"8\n\nSensorTyp" +
      "e\022\017\n\013TEMPERATURE\020\000\022\t\n\005LIGHT\020\001\022\016\n\nLUMINOS" +
      "ITY\020\002\"a\n\004time\022\017\n\007seconds\030\001 \002(\005\022\017\n\007minute" +
      "s\030\002 \002(\005\022\r\n\005hours\030\003 \002(\005\022\013\n\003day\030\004 \002(\005\022\r\n\005m" +
      "onth\030\005 \002(\005\022\014\n\004year\030\006 \002(\005\"\231\001\n\016CommandMess" +
      "age\022,\n\007command\030\001 \002(\0162\033.CommandMessage.Co" +
      "mmandType\022\032\n\tparameter\030\002 \001(\0132\007.Sensor\"=\n" +
      "\013CommandType\022\r\n\tGET_STATE\020\000\022\r\n\tSET_STATE" +
      "\020\001\022\020\n\014SENSOR_STATE\020\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Sensor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sensor_descriptor,
        new java.lang.String[] { "Type", "Id", "State", "Data", });
    internal_static_time_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_time_descriptor,
        new java.lang.String[] { "Seconds", "Minutes", "Hours", "Day", "Month", "Year", });
    internal_static_CommandMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CommandMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandMessage_descriptor,
        new java.lang.String[] { "Command", "Parameter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
